import { Injectable } from '@angular/core';
import type { WidgetCatalogEntry } from '../widgets.types';

const CATALOG: readonly WidgetCatalogEntry[] = [
  {
    id: 'map',
    nameKey: 'shell.control.map',
    nameFallback: 'Map',
    summaryKey: 'widget.catalog.map.summary',
    summaryFallback: 'The map of places and media.',
    bodyKey: 'widget.catalog.map.body',
    bodyFallback: 'The map is the home page. Its icon stays on the rail.',
    placement: 'top',
    rail: 'fixed',
    allowed: true,
  },
  {
    id: 'projects',
    nameKey: 'shell.control.projects',
    nameFallback: 'Projects',
    summaryKey: 'widget.catalog.projects.summary',
    summaryFallback: 'Projects for the organization.',
    bodyKey: 'widget.catalog.projects.body',
    bodyFallback: 'Projects stay on the rail.',
    placement: 'top',
    rail: 'fixed',
    allowed: true,
  },
  {
    id: 'media',
    nameKey: 'shell.control.media',
    nameFallback: 'Media',
    summaryKey: 'widget.catalog.media.summary',
    summaryFallback: 'The media library.',
    bodyKey: 'widget.catalog.media.body',
    bodyFallback: 'Media stays on the rail.',
    placement: 'top',
    rail: 'fixed',
    allowed: true,
  },
  {
    id: 'workers',
    nameKey: 'widget.catalog.workers',
    nameFallback: 'Workers',
    summaryKey: 'widget.catalog.workers.summary',
    summaryFallback: 'People who work in the organization.',
    bodyKey: 'widget.catalog.workers.body',
    bodyFallback: 'Workers join the bottom of the left rail after the organization adds them.',
    placement: 'bottom',
    rail: 'installable',
    allowed: true,
  },
  {
    id: 'organisation',
    nameKey: 'widget.catalog.organisation',
    nameFallback: 'Organisation',
    summaryKey: 'widget.catalog.organisation.summary',
    summaryFallback: 'The organization, its roles, and its settings.',
    bodyKey: 'widget.catalog.organisation.body',
    bodyFallback: 'Organisation joins the bottom of the left rail after the organization adds it.',
    placement: 'bottom',
    rail: 'installable',
    allowed: true,
  },
  {
    id: 'vehicles',
    nameKey: 'widget.catalog.vehicles',
    nameFallback: 'Vehicles',
    summaryKey: 'widget.catalog.vehicles.summary',
    summaryFallback: 'Vehicles and the media attached to them.',
    bodyKey: 'widget.catalog.vehicles.body',
    bodyFallback: 'A vehicle has one place on the map and any number of media items.',
    placement: 'unplaced',
    rail: 'installable',
    allowed: true,
  },
  {
    id: 'boats',
    nameKey: 'widget.catalog.boats',
    nameFallback: 'Boats',
    summaryKey: 'widget.catalog.boats.summary',
    summaryFallback: 'Boats and the media attached to them.',
    bodyKey: 'widget.catalog.boats.body',
    bodyFallback: 'A boat has one place on the map and any number of media items.',
    placement: 'unplaced',
    rail: 'installable',
    allowed: true,
  },
  {
    id: 'material',
    nameKey: 'widget.catalog.material',
    nameFallback: 'Material',
    summaryKey: 'widget.catalog.material.summary',
    summaryFallback: 'Material and where it sits.',
    bodyKey: 'widget.catalog.material.body',
    bodyFallback: 'A material stock has one place on the map and any number of media items.',
    placement: 'unplaced',
    rail: 'installable',
    allowed: true,
  },
  {
    id: 'storage-locations',
    nameKey: 'widget.catalog.storageLocations',
    nameFallback: 'Storage locations',
    summaryKey: 'widget.catalog.storageLocations.summary',
    summaryFallback: 'Yards, warehouses, containers, and rooms.',
    bodyKey: 'widget.catalog.storageLocations.body',
    bodyFallback: 'A storage location has one place on the map and any number of media items.',
    placement: 'unplaced',
    rail: 'installable',
    allowed: true,
  },
  {
    id: 'buildings',
    nameKey: 'widget.catalog.buildings',
    nameFallback: 'Buildings',
    summaryKey: 'widget.catalog.buildings.summary',
    summaryFallback: 'Buildings and the media attached to them.',
    bodyKey: 'widget.catalog.buildings.body',
    bodyFallback: 'A building has one place on the map and any number of media items.',
    placement: 'unplaced',
    rail: 'installable',
    allowed: true,
  },
];

/** Static catalog. Not a table. */
@Injectable({ providedIn: 'root' })
export class WidgetsCatalogAdapter {
  entries(): readonly WidgetCatalogEntry[] {
    return CATALOG;
  }
}
