import type { ActionDefinition } from '../../action-system/action-types';
import type {
  MapActionContext,
  MapMenuActionId,
  MarkerActionContext,
  MarkerMenuActionId,
} from './map-workspace-actions.types';

export const MAP_MENU_ACTION_DEFINITIONS: ReadonlyArray<
  ActionDefinition<MapActionContext, MapMenuActionId>
> = [
  {
    id: 'create_marker_here',
    section: 'primary',
    priority: 0,
    icon: 'add_location',
    fallbackLabel: 'Media Marker hier erstellen',
    visibleWhen: () => true,
  },
  {
    id: 'zoom_house',
    section: 'primary',
    priority: 1,
    icon: 'center_focus_strong',
    fallbackLabel: 'Hierhin zoomen (Hausnaehe)',
    visibleWhen: () => true,
  },
  {
    id: 'zoom_street',
    section: 'primary',
    priority: 1,
    icon: 'zoom_in',
    fallbackLabel: 'Hierhin zoomen (Strassennaehe)',
    visibleWhen: () => true,
  },
  {
    id: 'copy_address',
    section: 'secondary',
    priority: 0,
    icon: 'content_copy',
    fallbackLabel: 'Adresse kopieren',
    visibleWhen: () => true,
  },
  {
    id: 'copy_gps',
    section: 'secondary',
    priority: 0,
    icon: 'content_copy',
    fallbackLabel: 'GPS kopieren',
    visibleWhen: () => true,
  },
  {
    id: 'open_google_maps',
    section: 'secondary',
    priority: 0,
    icon: 'open_in_new',
    fallbackLabel: 'In Google Maps oeffnen',
    visibleWhen: () => true,
  },
];

export const MARKER_MENU_ACTION_DEFINITIONS: ReadonlyArray<
  ActionDefinition<MarkerActionContext, MarkerMenuActionId>
> = [
  {
    id: 'open_details_or_selection',
    section: 'primary',
    priority: 0,
    icon: 'open_in_new',
    fallbackLabel: 'Details oeffnen',
    visibleWhen: (context) => context.contextType === 'map_marker',
  },
  {
    id: 'open_details_or_selection',
    section: 'primary',
    priority: 0,
    icon: 'grid_view',
    fallbackLabel: 'Auswahl oeffnen',
    visibleWhen: (context) => context.contextType === 'map_cluster',
  },
  {
    id: 'open_in_media',
    section: 'primary',
    priority: 1,
    icon: 'open_in_new',
    fallbackLabel: 'Open in media',
    visibleWhen: (context) => context.contextType === 'map_marker',
  },
  {
    id: 'zoom_house',
    section: 'primary',
    priority: 1,
    icon: 'center_focus_strong',
    fallbackLabel: 'Hierhin zoomen (Hausnaehe)',
    visibleWhen: () => true,
  },
  {
    id: 'zoom_street',
    section: 'primary',
    priority: 1,
    icon: 'zoom_in',
    fallbackLabel: 'Hierhin zoomen (Strassennaehe)',
    visibleWhen: () => true,
  },
  {
    id: 'assign_to_project',
    section: 'primary',
    priority: 0,
    icon: 'folder_open',
    fallbackLabel: 'Projekt hinzufuegen...',
    visibleWhen: () => true,
  },
  {
    id: 'change_location_map',
    section: 'primary',
    priority: 1,
    icon: 'pin_drop',
    fallbackLabel: 'Change GPS location',
    visibleWhen: (context) => !context.isMultiSelection,
  },
  {
    id: 'change_location_address',
    section: 'primary',
    priority: 1,
    icon: 'search',
    fallbackLabel: 'Change address',
    visibleWhen: (context) => !context.isMultiSelection,
  },
  {
    id: 'copy_address',
    section: 'secondary',
    priority: 0,
    icon: 'content_copy',
    fallbackLabel: 'Adresse kopieren',
    visibleWhen: (context) => !context.isMultiSelection,
  },
  {
    id: 'copy_gps',
    section: 'secondary',
    priority: 0,
    icon: 'content_copy',
    fallbackLabel: 'GPS kopieren',
    visibleWhen: (context) => !context.isMultiSelection,
  },
  {
    id: 'open_google_maps',
    section: 'secondary',
    priority: 0,
    icon: 'open_in_new',
    fallbackLabel: 'In Google Maps oeffnen',
    visibleWhen: (context) => !context.isMultiSelection,
  },
  {
    id: 'delete_media',
    section: 'destructive',
    priority: 0,
    icon: 'delete',
    fallbackLabel: 'Foto loeschen',
    visibleWhen: () => true,
  },
  {
    id: 'remove_from_project',
    section: 'destructive',
    priority: 0,
    icon: 'remove_circle_outline',
    fallbackLabel: 'Remove from project(s)',
    visibleWhen: () => true,
  },
];
