/**
 * The words that make the token before them part of the street name (`Lange` + `Gasse`).
 * One owner: the token classifier used to keep a second, shorter copy of this list, and the copy
 * had no `strasse` — so `Wiener Strasse` and `Lerchenfelder Strasse` both became the street
 * `Strasse` and shared one grouping key.
 */
export const STREET_KEYWORDS = new Set<string>([
  'gasse',
  'gassen',
  'gürtel',
  'guertel',
  'steig',
  'straße',
  'straßen',
  'strasse',
  'strassen',
  'str',
  'str.',
  'platz',
  'plätze',
  'plaetze',
  'weg',
  'allee',
  'ring',
  'damm',
  'ufer',
  'zeile',
  'road',
  'street',
  'st',
  'st.',
  'avenue',
  'ave',
  'ave.',
  'drive',
  'dr',
  'dr.',
  'lane',
  'ln',
  'ln.',
  'boulevard',
  'blvd',
  'blvd.',
  'court',
  'ct',
  'ct.',
  'way',
]);
